name: Build and Test Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install Dependencies
      run: npm ci

    - name: Build Angular Application
      run: npm run build

    - name: Start Angular Server
      run: |
        nohup npm start &
        # Wait for the server to be available (optional but recommended)
        npx wait-on http://localhost:4200
      env:
        CI: true
      
    - name: Run Tests
      run: npm test
